#Guess the number - game

import random


def guess_number(x):

    print ("====================")
    print ("WELCOME TO THE GAME")
    print ("===================")
    print ("your goal is to guess the number generated by computer")

    random_number = random.randint(1,x)   # -> numero aleatorio entre 1 y x

    attemp = 0

    while attemp != random_number:
        attemp = int(input(f"Guess a number between 1 and {x}: "))
        if attemp < random_number:
            print ("Try again, maybe with a higher number")
        elif attemp > random_number:
            print ("Try again, maybe with a lower number")

    print (f"Congratulations! you guess the number!")


guess_number(20)



